CC=clang
CFLAGS=-std=c99 -Wall -Wextra -g
LDFLAGS=
EXEC=test_morse

# Makefile a completer
.PHONY: clean enonce
enonce:
	@echo "Completez d'abord le Makefile pour compiler cet exercice."

clean:
	rm -f *~ *.o $(EXEC)
