# Completer le Makefile effectuant les operations suivantes :
# - Generation de 2 versions de l'executable : <nomexecutable> et <nomexecutable>_fsanitize
# - <nomexecutable> : avec options de compilation standards et mode debogage pour utilisation de valgrind
# - <nomexecutable>_fsanitize : avec options ligne ci-dessus + options mode debogage fsanitize
# - Regle clean : supprimer les fichiers .o et les executables et fichier preprocesseur generes 
CC=clang
